title: "Analytics and Integrative Machine Learning"
author: AIML @ NCAR
logo: ../NCAR_UCAR_LIVERY/Logos/Contemporary Logos/NCAR/Dark Logo/NCAR-contemp-logo-blue.png
execute:
  execute_notebooks: "off"